version: '2'
services:
    optjob-app:
        image: optjob
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://optjob-mysql:3306/optjob?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    optjob-mysql:
        extends:
            file: mysql.yml
            service: optjob-mysql
